# IK Analyzer 扩展配置
analysis_ik:
  # 字典配置
  dictionary:
    # 用户可以在这里配置自己的扩展字典
    ext_dict: ""
    # 用户可以在这里配置自己的扩展停止词字典
    ext_stop_word: ""
    # 用户可以在这里配置远程扩展字典
    remote_ext_dict: ""
    # 用户可以在这里配置远程扩展停止词字典
    remote_ext_stop_word: ""